[env._]
path = ["{{config_root}}/node_modules/.bin"]

[tasks.apalache]
run_windows = "{{ env.HOME }}/.quint/apalache-dist-0.51.1/apalache/bin/apalache-mc.bat server --port=8822"

[tasks.clean]
run = [
  "fd -I -e aux -e dvi -e log -e pdf -e tex -e out -x rm {}",
  "fd -I -t d states -x rm -rf {}",
]